name: BASeCamp Survival Chests
main: com.BASeCamp.SurvivalChests.BCRandomizer
version: 1.1
commands:
      repopchests:
        description: repopulates chests in loaded chunks.
      startgame:
        description: prevents player PvP for the given number of seconds, while initializing the data for a new Survival game.
      teamsplit:
        description: splits online players into two teams, and announces the results.
      strikecreepers:
        description: turns all present creepers into super creepers.